### ISSUE TITLE
stands.fosdem.org does not update

### ISSUE THREAD

**Issue by tpgxyz** [FOSDEM/stands-website#11]
Hi,

id like to mention that https://stands.fosdem.org/stands/openmandriva/ does not show latest changes introduced by PR #9 
Update is disabled till some date or what ?

**Comment by pieterdp** [comment]
Hello,

It is still a manual process, but it will be fixed.

Pieter

**Comment by pieterdp** [comment]
Hello,

Script has been created and configured.

Pieter
