### ISSUE TITLE
Updated content for FreeBSD

### ISSUE THREAD

**Issue by Jehops** [FOSDEM/stands-website#135]
Hello,

Pull request #120 was committed in https://github.com/FOSDEM/stands-website/pull/120/commits/85a35f1a1db5698882c035416c5ac173b5405ee1, which was intended to updated the content for FreeBSD's stand.  However, https://stands.fosdem.org/stands/freebsd_project/ stills shows the old content.  Did I do something wrong?

Regards,

Joe

**Comment by pieterdp** [comment]
Hello,

This should now be fixed, can you confirm?

Kind regards,

Pieter De Praetere

**Comment by Jehops** [comment]
Hi.  Looks good.  Thank you.

**Comment by Jehops** [comment]
Hello Pieter,

The content on our virtual stand seems to have been reverted back to the old copy.  Could you take a look?

Thank you,

Joe

**Comment by pieterdp** [comment]
Does it work now?

**Comment by Jehops** [comment]
Yes.  It's pulling the submodule from the newer repository again.  Thanks.
