### ISSUE TITLE
How to upload videos for stands ?

### ISSUE THREAD

**Issue by rzr** [FOSDEM/stands-website#141]
Hi,
It looks like there is something broken in stands, there are no video published at:

https://video.fosdem.org/2022/stands/

I expected to see some last like last year:
http://video.fosdem.org/2021/stands/

Anyway before I am confusing readers, please refer to the instructions which i have read at:
https://github.com/FOSDEM/stands-website/blob/master/README.md#video

## Penta

From my penta dashboard https://penta.fosdem.org/submission/FOSDEM22/events 
I can see 6 events about stands

- 1 "Welcome to *" miss the upload link in the "Schedule"'s panel (problem 1)
- 2..6 : "Stand Video *" have the upload link 

## Upload

So I tried to upload stand's video (1 to 4), for each of them I can see the upload callback:
{
https://upload.video.fosdem.org/i/*/update
Stands recordings for 'FOSDEM 2022' videos
Stand recording for 'Stand Video * for * Project stand'
Thank you for sending your files
These files will now be injected into the system.
}

## Status

According to the status page:
https://upload.video.fosdem.org/overview

All entries in form of "Prerecording for talk 'Stand Video *" are ignored, 
I think this is not expected (Problem 2)

While all  other entries in form of "Prerecording for talk 'Welcome to *" have  "waiting for files" status
but there is no way to upload those (see Problem 1 described above)

# Actions

I (@rzr) have reported this to a couple of time in fosdem's IRC room (to markvandenborre, agk, wouter,...)
but I thought it would be easier to use a ticket to coordinate needed work.
Feel free to ask me for more testing.

Regards

**Comment by kergon** [comment]
Don't fret - the publication step hasn't been turned on yet. (Should happen this week.)

But please don't edit the titile of the event - you will need to change those back to the original templated ones ('Stand Video N for...") or stuff won't work.

Nothing uses subtitle so anything you put there will just be ignored.

Welcome talks don't have videos.

**Comment by rzr** [comment]
Thanks for clarification, I'll confirm when It's working

**Comment by rzr** [comment]
update: Some videos are uploaded in:

https://video.fosdem.org/2022/stands/S.nextcloud/

Despite they are marked ignored in

https://upload.video.fosdem.org/overview

```
Prerecording for talk 'Stand Video 1 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 6:00:00 PM | 2/5/2022, 7:00:00 PM | ignored | waiting
-- | -- | -- | -- | -- | -- | --
Prerecording for talk 'Stand Video 2 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 7:00:00 PM | 2/5/2022, 8:00:00 PM | ignored | waiting
Prerecording for talk 'Stand Video 3 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 8:00:00 PM | 2/5/2022, 9:00:00 PM | ignored | waiting
Prerecording for talk 'Stand Video 4 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 9:00:00 PM | 2/5/2022, 10:00:00 PM | ignored | waiting
Prerecording for talk 'Stand Video 5 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 10:00:00 PM | 2/5/2022, 11:00:00 PM | ignored | waiting
```

I just summited  to
https://upload.video.fosdem.org/r/*/update
"Stand recording for 'Stand Video 4 for Oniro Project stand' "
let's see how it goes and I'll keep you updated here

**Comment by kergon** [comment]
You need to pick the stands dropdown at the top of that page.  There are two separate systems, each sees the full list, one process talks, the other processes videos.

**Comment by kergon** [comment]
publishing...waiting.
But email video@ for support with that system.

**Comment by rzr** [comment]
ok this small detail helps, I can see it now:

```
Stand recording for 'Stand Video 1 for Nextcloud Hub stand' |   | S.nextcloud | 2/5/2022, 6:00:00 PM | 2/5/2022, 7:00:00 PM | done | waiting
```

For the records some of mine are have "publishing" state, I guess it's the expected flow:

- "ignored", "waiting_for_files", "uploading", "preview", "publishing", "done" 
-  (that would help to be documented, I can patch doc if you confirm it's correct)

```
Stand recording for 'Stand Video 1 for Oniro Project stand' |   | S.oniro | 2/5/2022, 6:00:00 PM | 2/5/2022, 7:00:00 PM | waiting_for_files | waiting
Stand recording for 'Stand Video 2 for Oniro Project stand' |   | S.oniro | 2/5/2022, 7:00:00 PM | 2/5/2022, 8:00:00 PM | publishing | waiting
Stand recording for 'Stand Video 4 for Oniro Project stand' |   | S.oniro | 2/5/2022, 9:00:00 PM | 2/5/2022, 10:00:00 PM | publishing | waiting
Stand recording for 'Stand Video 5 for Oniro Project stand' |   | S.oniro | 2/5/2022, 10:00:00 PM | 2/5/2022, 11:00:00 PM | publishing | waiting
```

For video 2 (https://penta.fosdem.org/submission/FOSDEM22/event/13372 ) 
I can see the " Final Video URL " link to https://validate.video.fosdem.org/*.mp4 
but there is  a 404 error (an error page is missing to explain what's happening (maybe already validated?))

I'll email if I don't see progress, thx anyway for support

ps: https://chat.fosdem.org/#/room/#stands:fosdem.org is not open to community

**Comment by rzr** [comment]
Thx @kergon  for fixing this, I can see 

https://video.fosdem.org/2022/stands/oniro/stand_video_oniro_video3.webm

I'll check for others and will keep you updated

**Comment by rzr** [comment]
I need more support to upload other videos (previously uploaded), I mailed v@f.o

They are still in "publishing" state according to: 
- https://upload.video.fosdem.org/overview

**Comment by rzr** [comment]
Some updates, I think this issue can be closed , I managed to inline 3 videos (some transcoded mp4 files are missing but I guess they will appear soon)

https://stands.fosdem.org/stands/oniro_project/

ps: is it possible to delete this duplicated one:

https://video.fosdem.org/2022/stands/oniro/stand_video_oniro_video5.*

**Comment by ptitSeb** [comment]
I do have issue uploading video. I suppose it's due to my slow upload bandwidth. The video is in mp4 format and weight 502MB.  The best I have in upload speed is around 10 Mb/s, using my phone connection, so that's still a 9min upload... 
But I get a "502 - Bad Gateway" response after sometimes. Is there a way to change the timeout (or is there a way to use ftp transfert or something like that?)

**Comment by rzr** [comment]
> I do have issue uploading video. I suppose it's due to my slow upload bandwidth. 

Salut, I suppose so, because it worked for me, I could upload file for you if you can rsync/scp it to me

**Comment by ptitSeb** [comment]
> > I do have issue uploading video. I suppose it's due to my slow upload bandwidth.
> 
> Salut, I suppose so, because it worked for me, I could upload file for you if you can rsync/scp it to me

I have uploaded my video there: http://ptitseb.openpandora.org/FosdemVideo2022.mp4
Can you upload it as Video 1 for Box86 stand?

**Comment by rzr** [comment]
> Can you upload it as Video 1 for Box86 stand?

I'll need your password for that find me in #fosdem irc

**Comment by ptitSeb** [comment]
That's doesn't look like a viable solution, but thanks for the proposition.

Can the upload page be modified so it can accept an url for the upload, along with the local file?

**Comment by rzr** [comment]
> Can the upload page be modified so it can accept an url for the upload, along with the local file?

You can ask in IRC's #fosdem-video but it's unlikely to happen.

I am closing this issue because the upload method described is working for stands
