### ISSUE TITLE
embedded video doesn't work

### ISSUE THREAD

**Issue by jospoortvliet** [FOSDEM/stands-website#16]
See https://github.com/FOSDEM/stands-website/pull/14 - The nice videos do NOT show up on stands.fosdem.org ;-)

Should I embed YouTube videos? That just seems nasty, bringing YouTube on the pages... Can you debug this perhaps? It works in Hugo. The website inspect console says:

```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
``

I don't know how to work around that and make it show up anyhow... It'd be nice to have them there ;-)

If you won't allow scripts, I'll make it images & link to the YouTube videos - but again, I prefer to use this videodelivery.net as they only store some super basic information and delete it after some time, instead of being evil-tracking-YouTube-Google. Unfortunately I can't deep link to those videos so linking would be YouTube. Pls advise!

**Comment by kergon** [comment]
We won't be embedding youtube - sorry.
We may have an alternative solution involving video.fosdem.org which can be embedded IIRC.

**Comment by jospoortvliet** [comment]
> We won't be embedding youtube - sorry.
> We may have an alternative solution involving video.fosdem.org which can be embedded IIRC.

well, I'd rather avoid youTube too, that is why I used the same as what we use on our website:

```
<stream src=\"4b66104c586170a4dc5b6ebbed80b193\" controls preload poster=\"https://nextcloud.com/wp-content/themes/next//assets/img/features/homeoffice-video.png\">
</stream> <script data-cfasync=\"false\" defer type=\"text/javascript\" src=\"https://embed.videodelivery.net/embed/r4xu.fla9.latest.js?video=4b66104c586170a4dc5b6ebbed80b193\"></script>
```

Could a CSP exception be made for that? (I have no idea how that works...)

**Comment by jospoortvliet** [comment]
Otherwise, uploading the videos myself to video.fosdem.org and embedding that would be great, any pointers to how-to-do-that would be very welcome.

**Comment by melcorr** [comment]
Is there any docs about uploading videos to video.fosdem.org and then embedding to our stand pages?

**Comment by sharanf** [comment]
Looking at video content too - has anyone found any instructions or got this working yet?

**Comment by kaushiksanthanam** [comment]
looking to upload video. Please let us know instructions!

**Comment by pieterdp** [comment]
Hi,

We've updated the README (and sent the mail to the mailing list).

If you have further questions, let us know!

Pieter
