### ISSUE TITLE
GNOME Foundation Stand has no Logo

### ISSUE THREAD

**Issue by ovflowd** [FOSDEM/stands-website#165]
Hi there 👋 

For some reason, our Stand Logo is showing a placeholder. But checking the path on our Markdown file, and checking the Git Submodule, the links seem correct. Could you folks please check why the logo is not rendering? 😅 

Thank you!

**Comment by pieterdp** [comment]
Hello,

It seems that the main repo is missing `the_gnome_foundation.md` in `content/stands`. For reasons that I can't quite explain, that file is used for some of the variables on the overview pages (but not the entry itself).

Creating a pull requests that adds that file to `content/stands` and removing `show_on_overview` in the file in your repo will fix the issue. The contents will normally be overridden by whatever you put in your repo.

Pieter

**Comment by pieterdp** [comment]
Hello,

Has been fixed.

Pieter

**Comment by ovflowd** [comment]
Hi @pieterdp for some reason I didn't get a notification 😅

Thanks for fixing the issue! I really appreciate it! 🙏

Cheers!!
