### ISSUE TITLE
Ubuntu stand is not getting loaded from the submodule

### ISSUE THREAD

**Issue by tcarreira** [FOSDEM/stands-website#171]
Despite having the git submodule, the ubuntu stand is not reflected on the website

**Comment by tcarreira** [comment]
Hey @pieterdp Thanks for accepting #172. 👍 

But it looks like it did not reflect on the [fosdem website](https://stands.fosdem.org/stands/ubuntu/). 
Would you mind giving a help here? 

What script does the cron run?, so I can debug it better

**Comment by kergon** [comment]
the website build was broken by a different module earlier but other things got in the way before I could deal with it

**Comment by kergon** [comment]
the problem is people putting bad characters into yaml

**Comment by kergon** [comment]
2 bad yaml files - deleted them and built site without - has that got whatever you changed?

**Comment by kergon** [comment]
it's a problem when a submodule contains unparseable content

**Comment by tcarreira** [comment]
The website seems fixed now :D 
Thank you.

Will it fetch the latest content from `main` automagically? (I believe so, I'll wait for the next hour to confirm it ;) )

**Comment by tcarreira** [comment]
> the problem is people putting bad characters into yaml

What do you think about adding some tests on MR?
A simple test, like running hugo build

**Comment by kergon** [comment]
if it's easy to do sure

**Comment by tcarreira** [comment]
I'll make a PR as soon as I have some spare time ;)

**Comment by kergon** [comment]
it'll not pull updates at the moment - I just fixed the yaml in the checkout, ran hugo, but a moment later the script came in and wiped my changes

**Comment by kergon** [comment]
openuk / libresoc need PRs to fix their index.md yaml

**Comment by kergon** [comment]
- a colon in a line and a couple of non-indented lines

**Comment by tcarreira** [comment]
I made a PR for those tests: #178 with a separate issue #177

I will close this issue, it was resolved and the website looks up to date.
Thank you for your effort
