### ISSUE TITLE
OW2 stand not listed on https://stands.fosdem.org/stands/

### ISSUE THREAD

**Issue by amottier** [FOSDEM/stands-website#180]
OW2 Open Source Community stand is not listed on https://stands.fosdem.org/stands/ but is listed on https://fosdem.org/2022/stands/

I'm wondering if it has anything to do with our [_index.md](https://gitlab.ow2.org/ow2/fosdem/ow2-fosdem-stand-content/-/blob/master/_index.md) page?

Thank you!

**Comment by philippedeswert** [comment]
Looks like the git submodule points to a commit from last year. I also believe we need a ow2.md or similar file in /content/stands/ and the show_on_overview on false or removed in the _index.md page.

@pieterdp Can you fix the submodule? And did I remember right the show_on_overview thing?

**Comment by amottier** [comment]
@philippedeswert even if GitHub refers to a commit from last year in the OW2 submodule the content of https://stands.fosdem.org/stands/ow2_open_source_community/ correctly display the update we made only recently. I guess that the submodule is update as part of stands web pages generation.

The Eclipse Foundation stand is correctly listed on https://stands.fosdem.org/stands/ and their [Git repository](https://github.com/EclipseFdn/fosdem2021-content/tree/main) only include a single `_index.md` file and this file has `show_on_overview: true`. So I don't think I need to add an `ow2.md` file. Also `show_on_overview` was not included in our `_index.md` file until recently so I think it has not impact on our issue.

**Comment by pieterdp** [comment]
Hello,

This has now been fixed, but you must remove the show_on_overview in your _index.md. An ow2.md file was necessary to ensure it's listed everywhere. This has to do with how Hugo operates.

Kind regards,

Pieter De Praetere

**Comment by gibello** [comment]
Hello @pieterdp ,
We removed the show_on_overview, but now:
- The generated ow2.md links to an old content (https://stands.fosdem.org/stands/ow2/ ).
- The real content of the stand is at https://stands.fosdem.org/stands/ow2_open_source_community/ , and properly linked from Fosdem main page (https://fosdem.org/2022/live/#stands then go to OW2).

So, I am wondering why this "ow2.md", shoudn't it be "ow2_open_source_community.md" instead?
Regards,
Pierre-Yves Gibello

**Comment by pieterdp** [comment]
Hello,

This should now be fixed. But I'd keep a candle lighted.

Pieter

**Comment by amottier** [comment]
Your candle did the trick :laughing: Thanks a lot for your help :+1:
