### ISSUE TITLE
schul-frei links

### ISSUE THREAD

**Issue by bene000** [FOSDEM/stands-website#187]
Links from the schul-frei stand to the videos and the welcoming event do not work. The URL on the stand page that should redirect to the event is https://fosdem.org/2022/schedule/room/sschul-frei/

But the real URL for the event is https://fosdem.org/2022/schedule/room/sschulfrei/

It is the same way with the linking for our uploaded videos.

The current URL is  https://video.fosdem.org/2022/stands/schul-frei but it should be https://video.fosdem.org/2022/stands/schulfrei

**Comment by pieterdp** [comment]
Hello,

You'll have to patch your _index.md file:
`chatroom: schul-frei` should become `chatroom: schulfrei`

This will fix the problem.

Pieter
