### ISSUE TITLE
What is the recommended logo image size ? 

### ISSUE THREAD

**Issue by atodorov** [FOSDEM/stands-website#5]
FOSDEM's `cogweel.png` appears to be 91x93 pixes and gets stretched to 185x189 on the main stands page.

Should we size our logos accordingly ?

**Comment by tpgxyz** [comment]
Good question. On my local `hugo serve ` copy all logos are displayed with their original size, nothing crops them to one standard size.

**Comment by pieterdp** [comment]
Hello,

The logo should be max. 200x200px in size.

Pieter

**Comment by atodorov** [comment]
> 
> The logo should be max. 200x200px in size.

That's what I have by accident. Thanks for clearing this up. Closing this issue.
