### ISSUE TITLE
Some small problems

### ISSUE THREAD

**Issue by bittin** [FOSDEM/stands-website#77]
RaphGro
there's a typo, it's "badge" not "bandge", see link. https://fosdem.org/2021/schedule/event/fedora_welcome/

RaphGro

mh, isn't it Check_MK (any more) instead of Checkmk? https://fosdem.org/2021/schedule/track/checkmk_stand/

checkmk according to their website

**Comment by pieterdp** [comment]
Hi,

These are under the control of the stand sadly :(

Pieter
